apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dotnetdemo
  name: dotnetdemodeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: dotnet-app
          image: acrcontainer28.azurecr.io/acrcontainer28:1.0.0
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: acr-secret