apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nithu99-rolebinding
  namespace: nithu
subjects:
- kind: ServiceAccount
  name: nithu99-serviceaccount
  namespace: nithu
roleRef:
  kind: Role
  name: nithu99-role
  apiGroup: rbac.authorization.k8s.io