apiVersion: apps/v1
kind: Deployment
metadata:
  name: nithu99
  namespace: nithu
  labels:
    app: nithu99
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nithu99
  template:
    metadata:
      labels:
        app: nithu99
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-label-key
                operator: In
                values:
                - node-label-value
      containers:
      - name: nithu99
        image: nithu99/dotnet-demo-app:v1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "300Mi"
          requests:
            cpu: "100m"
            memory: "300Mi"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: ENV_VARIABLE_1
          valueFrom:
            configMapKeyRef:
              name: nithu99-configmap
              key: ENV_VARIABLE_1
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: nithu99-secret
              key: SECRET_KEY
