apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nithu99-hpa
  namespace: nithu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nithu99
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50